# Generated by Django 4.1.3 on 2023-06-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_advocate'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='Regfee',
            field=models.CharField(default='Pending', max_length=100, null=True),
        ),
    ]
