# Generated by Django 4.1.3 on 2023-06-15 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_advocate_regfee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=100, null=True)),
                ('Description', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IPC_sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IPC', models.CharField(max_length=100, null=True)),
                ('Description', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=100, null=True)),
                ('Feedback', models.CharField(max_length=100, null=True)),
                ('Type', models.CharField(max_length=100, null=True)),
                ('date', models.CharField(max_length=100, null=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.userregistration')),
            ],
        ),
    ]
