# Generated by Django 4.1.3 on 2023-06-15 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_case_category_ipc_sections_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=100, null=True)),
                ('desc', models.CharField(max_length=100, null=True)),
                ('date', models.CharField(max_length=100, null=True)),
                ('advocate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.advocate')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.userregistration')),
            ],
        ),
    ]
