# Generated by Django 4.1.3 on 2023-06-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_case_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_request',
            name='request',
            field=models.CharField(default='pending', max_length=100, null=True),
        ),
    ]
