# Generated by Django 4.1.3 on 2023-06-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_case_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_request',
            name='request',
            field=models.CharField(default='Not_Updated', max_length=100, null=True),
        ),
    ]
