# Generated by Django 4.1.3 on 2023-06-22 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_case_request_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_details',
            name='rid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.case_request'),
        ),
        migrations.AddField(
            model_name='case_request',
            name='status',
            field=models.CharField(default='Not_Updated', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='case_request',
            name='request',
            field=models.CharField(default='pending', max_length=100, null=True),
        ),
    ]
