# Generated by Django 4.2.2 on 2023-08-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_feedback_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_details',
            name='status',
            field=models.CharField(default='Not_Paid', max_length=100, null=True),
        ),
    ]
