# Generated by Django 4.1.2 on 2024-03-02 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='aid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.advocate'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.userregistration'),
        ),
    ]
