# Generated by Django 4.1.2 on 2024-03-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_feedback_aid_feedback_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
        migrations.AddField(
            model_name='advocate',
            name='files',
            field=models.FileField(null=True, upload_to='profile'),
        ),
    ]
