# Generated by Django 4.1.2 on 2024-03-19 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_feedback_name_advocate_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('aid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.advocate')),
                ('rid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.case_request')),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.userregistration')),
            ],
        ),
    ]
